services:
  rtdbin:
    container_name: rtdbin
    image: ghcr.io/readthedocs-fr/bin:main
    links:
      - redis
    ports:
      - "8012:8012"
    environment:
      - RTDBIN_HOST=0.0.0.0
      - REDIS_HOST=redis
  redis:
    container_name: db
    image: redis
