# This workflow will run tests on every push or pull request and lint using ESLint.

name: Continuous Integration

on:
  push:
    paths:
      - '**.ts'
      - package.json
      - tsconfig.json
      - tsconfig.prod.json
      - rtdbin-docker-compose.yml
      - jest.config.json
      - '.github/workflows/**/*'
  pull_request:
    paths:
      - '**.ts'
      - package.json
      - tsconfig.json
      - tsconfig.prod.json
      - rtdbin-docker-compose.yml
      - jest.config.json
      - '.github/workflows/**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install dependencies
        run: npm i

      - name: Lint with ESLint
        run: npm run lint

      - name: Run tests
        run: |
          docker-compose -f rtdbin-docker-compose.yml up -d --build
          npm run test
          docker-compose -f rtdbin-docker-compose.yml down

      - name: Build
        run: npm run build -- --noEmit
