# This workflow will run tests on every push or pull request and lint using ESLint.

name: Continuous Integration

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Install Dependencies
        run: npm i

      - name: Lint with ESLint
        run: npm run lint

      - name: Run Tests
        run: npm run test

      - name: Build
        run: npm run build
