# This workflow will run unit tests in order to check if everything works as intended.

name: Unit Tests

on:
    push:
        paths: [src, test]
        tags-ignore: ["*"]
    pull_request:
        paths: [src, test]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 15

            - name: Install dependencies
              run: yarn install --immutable
